### ISSUE TITLE
AttributeError: 'BIN_Nonterminal' object has no attribute 'matches_category'

### ISSUE THREAD

**Issue by sverrirab** [vthorsteinsson/ReynirPackage#1]
Using the example code from https://greynir.is/doc/quickstart.html and the text from ruv.is:

my_text = "Ákæran var þingfest í Héraðsdómi Reykjaness í dag en fréttastofu er ekki kunnugt um hvort maðurinn játaði eða neitaði sök þar sem þinghaldið í málinu er lokað."

Gives the exception in the title.

**Comment by vthorsteinsson** [comment]
Quick update: The bug is probably found, but I need to do some more work before releasing a fresh update. Will comment here when it is ready.

**Comment by vthorsteinsson** [comment]
Fixed in version 1.1.0.
