### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'first'

### ISSUE THREAD

**Issue by sverrirab** [vthorsteinsson/ReynirPackage#2]
Using the example code from https://greynir.is/doc/quickstart.html and the text from ruv.is:

my_text = "Viðar Garðarsson , sem setti upp vefsíður fyrir Sigmund Davíð Gunnlaugsson í kjölfar birtingu Panamaskjalanna , segist ekki vita hvers vegna ákveðið var að segja að vefjunum væri haldið úti af stuðningsmönnum Sigmundar"

Gives the exception in the title.

**Comment by vthorsteinsson** [comment]
Fixed in version 1.1.0.
