### ISSUE TITLE
Doesn't recognise letter in house number as part of address

### ISSUE THREAD

**Issue by sveinbjornt** [vthorsteinsson/ReynirPackage#5]
Reynir doesn't identify alphabetic characters appended to house numbers as part of the address.

    >>> s = r.parse_single("Hann býr á Bárugötu 14.")
    >>> print(s.tree.view)
    P
    +-S-MAIN
      +-IP
        +-NP-SUBJ
          +-pfn_kk_et_nf: 'Hann'
        +-VP-SEQ
          +-VP
            +-so_0_et_p3: 'býr'
          +-PP
            +-fs_þgf: 'á'
            +-NP-ADDR
              +-gata_þgf_kvk: 'Bárugötu'
              +-tala: '14'
    +-'.'
    >>> s = r.parse_single("Hann býr á Bárugötu 14b.")
    >>> print(s.tree.view)
    P
    +-S-MAIN
      +-IP
        +-NP-SUBJ
          +-pfn_kk_et_nf: 'Hann'
        +-VP-SEQ
          +-VP
            +-so_0_et_p3: 'býr'
          +-PP
            +-fs_þgf: 'á'
            +-NP
              +-sérnafn: 'Bárugötu'
              +-tala: '14'
              +-no_et_þgf_hk: 'b'
    +-'.'
    >>> s = r.parse_single("Hann býr á Bárugötu 14A.")
    >>> print(s.tree.view)
    P
    +-S-MAIN
      +-IP
        +-NP-SUBJ
          +-pfn_kk_et_nf: 'Hann'
        +-VP-SEQ
          +-VP
            +-so_0_et_p3: 'býr'
          +-PP
            +-fs_þgf: 'á'
            +-NP
              +-no_et_þgf_kvk: 'Bárugötu'
              +-NP-POSS
                +-NP-MEASURE
                  +-mælieining: '14 A'
    +-'.'

**Comment by vthorsteinsson** [comment]
Thanks! Maybe the best way to solve this is to start in the Tokenizer package, adding a special token type for numbers with attached letters (I guess a single letter is enough, i.e. the regex for this token type would be `[1-9][0-9]*[A-Za-Z]`). In ReynirPackage, a new terminal type (e.g. `húsnúmer`) would then be added, matching both plain number tokens and this new token type. `húsnúmer` terminals would [only] be used in the grammar as a part of an address.

**Comment by vthorsteinsson** [comment]
The Tokenizer part of this has been fixed by @sveinbjornt 's PR to that repository: https://github.com/vthorsteinsson/Tokenizer/pull/3

**Comment by vthorsteinsson** [comment]
Fixed in @sveinbjornt 's PR, merged
